
"""
Generated by Antigravity v2
Updated with:
1. Fix for 'stretched' SVGs (removed preserveAspectRatio="none").
2. Enhanced Hull Theming (KCOM White Phone Box, Skyline).
3. Improved Animations (Staggered grids, Spotlight effect).
"""
import os
import shutil

print("Generating enhanced website (v2)...")

html = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Hull Web Fixers – Web Design, AI Automation &amp; Digital Ads</title>
<meta name="description" content="Hull's digital growth agency. Stunning websites, Google &amp; Facebook Ads, and AI automation for East Yorkshire businesses."/>
<!-- ═══ SECURITY META TAGS ═══ -->
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta http-equiv="X-Frame-Options" content="DENY">
<meta http-equiv="X-Content-Type-Options" content="nosniff">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta http-equiv="Permissions-Policy" content="camera=(), microphone=(), geolocation=(), payment=()">
<!-- ═══ FONTS ═══ -->
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link href="https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800;900&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&display=swap" rel="stylesheet"/>
<style>
:root{--bg:#060a14;--bg2:#0b1220;--bg3:#101a2e;--bdr:rgba(255,255,255,.07);--bdr2:rgba(255,255,255,.12);--amber:#F5A623;--amb2:#FCD34D;--teal:#0EA5E9;--tl2:#38BDF8;--txt:#94a3b8;--txt2:#cbd5e1;--white:#f1f5f9;--max:1200px;--r:1.25rem}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{overflow-x:hidden;font-size:16px;scroll-behavior:smooth}
body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--txt);overflow-x:hidden;line-height:1.7;-webkit-font-smoothing:antialiased}
h1,h2,h3,h4{font-family:'Syne',sans-serif;color:var(--white);line-height:1.1}
a{text-decoration:none;color:inherit}
img{max-width:100%;display:block}
.wrap{width:100%;max-width:var(--max);margin:0 auto;padding:0 clamp(1.25rem,5vw,2.5rem);position:relative}

/* ═══ UI ANIMATIONS ═══ */
.rv{opacity:0;transform:translateY(30px);transition:opacity .8s ease,transform .8s cubic-bezier(.2,.8,.2,1)}
.rv.vis{opacity:1;transform:translateY(0)}

/* Staggered children reveal */
.stagger-load > * {opacity:0;transform:translateY(20px);transition:opacity .6s ease,transform .6s ease}
.stagger-load.vis > * {opacity:1;transform:translateY(0)}
.stagger-load.vis > *:nth-child(1){transition-delay:0s}
.stagger-load.vis > *:nth-child(2){transition-delay:.1s}
.stagger-load.vis > *:nth-child(3){transition-delay:.2s}
.stagger-load.vis > *:nth-child(4){transition-delay:.3s}

/* Spotlight Hover Effect */
.card-spot{position:relative;overflow:hidden;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);transition:transform .4s,box-shadow .4s}
/* Mouse hover glow logic in JS creates --x, --y */
.card-spot::before{content:'';position:absolute;top:var(--y,0);left:var(--x,0);width:400px;height:400px;background:radial-gradient(circle,rgba(245,166,35,.15),transparent 70%);transform:translate(-50%,-50%);opacity:0;transition:opacity .4s;pointer-events:none;z-index:1}
.card-spot:hover::before{opacity:1}
.card-spot:hover{transform:translateY(-5px);border-color:rgba(245,166,35,.4);box-shadow:0 20px 40px -10px rgba(0,0,0,.5)}

#prog{position:fixed;top:0;left:0;height:3px;z-index:9999;width:0;background:linear-gradient(90deg,var(--amber),var(--teal))}
.navbar{position:fixed;top:0;left:0;right:0;z-index:800;background:rgba(6,10,20,.85);backdrop-filter:blur(16px);border-bottom:1px solid var(--bdr);transition:all .3s}
.navbar.scrolled{background:rgba(6,10,20,.98);border-bottom-color:rgba(245,166,35,.15)}
.navbar-inner{display:flex;align-items:center;justify-content:space-between;height:72px}
.logo-img{height:42px;width:auto}
.logo-text span:first-child{font-family:'Syne',sans-serif;font-weight:800;font-size:1.1rem;color:var(--white)}
.logo-text span:last-child{font-size:.65rem;color:var(--amber);letter-spacing:.05em;text-transform:uppercase}
.nav-links{display:flex;gap:2rem}
.nav-links a{font-weight:500;font-size:.9rem;color:var(--txt2);transition:color .2s}
.nav-links a:hover{color:var(--amber)}
.btn-nav{background:var(--amber);color:#0a0a0a;font-weight:700;padding:.6rem 1.4rem;border-radius:.6rem;transition:transform .2s,box-shadow .2s}
.btn-nav:hover{transform:translateY(-2px);box-shadow:0 8px 20px rgba(245,166,35,.3)}

/* Hero */
.hero{position:relative;padding:140px 0 100px;overflow:hidden;display:flex;align-items:center;min-height:95vh}
.hero-bg{position:absolute;inset:0;z-index:0;pointer-events:none}
/* Fixing the stretched bridge: use preserveAspectRatio */
.hero-bridge-svg{position:absolute;bottom:-5%;left:0;width:100%;height:auto;max-height:50vh;opacity:.08;pointer-events:none}
.hero-content{position:relative;z-index:10;display:grid;grid-template-columns:1.2fr 1fr;gap:4rem;align-items:center}
.hero h1{font-size:clamp(2.5rem,5vw,4.2rem);font-weight:900;line-height:1.1;margin-bottom:1.5rem}
.hero p{font-size:1.1rem;max-width:48ch;margin-bottom:2.5rem;color:var(--txt2)}
.grad-text{background:linear-gradient(135deg,#FFF 30%,var(--txt));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;color:transparent}
.grad-accent{background:linear-gradient(135deg,var(--amber),#FFD700);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;color:transparent}

/* HULL THEME: White Phone Box Icon */
.kcom-box{width:16px;height:24px;border:2px solid #fff;border-radius:2px 2px 0 0;position:relative;display:inline-block;vertical-align:middle;margin-right:6px}
.kcom-box::before{content:'';position:absolute;top:2px;left:2px;right:2px;height:14px;border:1px solid rgba(255,255,255,.5)}

.card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1.5rem}
.btn-primary{background:var(--amber);color:#0a0a0a;font-weight:800;padding:1rem 2.2rem;border-radius:.8rem;border:none;cursor:pointer;display:inline-flex;align-items:center;gap:.6rem;transition:all .3s;text-decoration:none}
.btn-primary:hover{transform:translateY(-3px);box-shadow:0 12px 30px rgba(245,166,35,.4)}

/* Services */
.svc-icon{width:56px;height:56px;border-radius:12px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.1);display:flex;align-items:center;justify-content:center;margin-bottom:1.5rem;font-size:1.8rem;transition:all .3s}
.card-spot:hover .svc-icon{background:var(--amber);color:#0a0a0a;border-color:var(--amber);transform:scale(1.1) rotate(-3deg)}

/* Footer Hull Skyline */
.hull-skyline{position:absolute;bottom:0;left:0;width:100%;height:120px;opacity:.05;pointer-events:none;z-index:0}

/* Mobile */
@media(max-width:1000px){.hero-content{grid-template-columns:1fr;text-align:center}.hero p{margin-left:auto;margin-right:auto}.card-grid{grid-template-columns:1fr 1fr}}
@media(max-width:650px){.card-grid{grid-template-columns:1fr}.nav-links{display:none}}

/* Forms */
input,select,textarea{width:100%;background:rgba(255,255,255,.03);border:1px solid var(--bdr);padding:1rem;color:#fff;border-radius:.8rem;font-family:inherit;margin-bottom:1rem;transition:.3s}
input:focus,textarea:focus{border-color:var(--amber);outline:none;background:rgba(245,166,35,.05)}

</style>
</head>
<body>

<div id="prog"></div>

<nav class="navbar">
<div class="wrap navbar-inner">
  <div style="display:flex;align-items:center;gap:.8rem">
    <img src="logo.png" alt="Hull Web Fixers" class="logo-img">
    <div class="logo-text" style="display:flex;flex-direction:column;line-height:1.2">
      <span>Hull Web Fixers</span>
      <span>Digital Growth Agency</span>
    </div>
  </div>
  <div class="nav-links">
    <a href="#services">Services</a>
    <a href="#portfolio">Our Work</a>
    <a href="#ai">AI Automation</a>
    <a href="#ads">Ads</a>
    <a href="#contact">Contact</a>
  </div>
  <a href="#contact" class="btn-nav">Get a Quote</a>
</div>
</nav>

<section class="hero">
  <!-- Hull Bridge Background SVG (Fixed Aspect Ratio) -->
  <svg class="hero-bridge-svg" viewBox="0 0 1440 320" preserveAspectRatio="xMidYMax slice" fill="none">
    <path d="M0,320 L0,200 Q360,100 720,200 T1440,200 L1440,320 Z" fill="rgba(245,166,35,0.03)" />
    <path d="M-100 320 Q 300 50 720 280 T 1540 320" stroke="rgba(245,166,35,0.1)" stroke-width="2" fill="none"/>
    <path d="M-100 320 Q 300 80 720 300 T 1540 320" stroke="rgba(14,165,233,0.1)" stroke-width="2" fill="none"/>
  </svg>
  
  <div class="wrap hero-content">
    <div class="rv">
      <div style="display:inline-flex;align-items:center;gap:.5rem;padding:.4rem 1rem;background:rgba(255,255,255,.05);border-radius:99px;font-size:.8rem;font-weight:600;margin-bottom:1.5rem;border:1px solid rgba(255,255,255,.1)">
        <span style="width:8px;height:8px;background:#22c55e;border-radius:50%;box-shadow:0 0 10px #22c55e"></span>
        Helping Hull Businesses Grow
      </div>
      <h1>
        <span class="grad-text">We Build.</span><br>
        <span class="grad-text">We Automate.</span><br>
        <span class="grad-accent">We Deliver.</span>
      </h1>
      <p>Stop relying on word-of-mouth. We build stunning websites, automated AI systems, and Google Ads campaigns that fill your diary.</p>
      <div style="display:flex;gap:1rem;flex-wrap:wrap;justify-content:center;margin-bottom:2rem">
         <a href="#contact" class="btn-primary">Start Your Growth</a>
         <a href="#portfolio" style="padding:1rem 2rem;border:1px solid var(--bdr);border-radius:.8rem;font-weight:600;display:flex;align-items:center;gap:.5rem;color:var(--txt2);text-decoration:none">View Portfolio <span class="material-symbols-outlined">arrow_forward</span></a>
      </div>
      <div style="display:flex;align-items:center;gap:1.5rem;font-size:.85rem;color:var(--txt2);justify-content:center">
        <span><i class="kcom-box"></i>From HU1 to HU17</span>
        <span style="display:flex;align-items:center;gap:4px"><span class="material-symbols-outlined" style="color:var(--amber);font-size:1.1rem">bolt</span>Fast Turnaround</span>
        <span style="display:flex;align-items:center;gap:4px"><span class="material-symbols-outlined" style="color:var(--amber);font-size:1.1rem">verified</span>No Jargon</span>
      </div>
    </div>
    
    <div class="rv" style="transition-delay:.2s">
      <!-- Animated Stats Card -->
      <div style="background:linear-gradient(145deg,rgba(255,255,255,.05),rgba(255,255,255,.01));border:1px solid rgba(255,255,255,.1);border-radius:1.5rem;padding:2rem;position:relative;overflow:hidden">
        <div style="position:absolute;top:0;right:0;width:150px;height:150px;background:radial-gradient(circle,rgba(14,165,233,.2),transparent 70%);filter:blur(20px)"></div>
        <div style="display:flex;align-items:center;gap:.8rem;margin-bottom:1.5rem;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:1rem">
          <div style="width:12px;height:12px;border-radius:50%;background:#ef4444"></div>
          <div style="width:12px;height:12px;border-radius:50%;background:#f59e0b"></div>
          <div style="width:12px;height:12px;border-radius:50%;background:#22c55e"></div>
          <div style="margin-left:auto;background:rgba(0,0,0,.3);padding:.2rem .8rem;border-radius:6px;font-size:.7rem;font-family:monospace;color:#64748b">dashboard.exe</div>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem">
           <div style="background:rgba(0,0,0,.2);padding:1rem;border-radius:1rem">
             <div style="font-size:.75rem;color:#94a3b8">New Leads</div>
             <div style="font-size:1.8rem;font-weight:800;color:#fff">128</div>
             <div style="font-size:.7rem;color:#22c55e">+24% this week</div>
           </div>
           <div style="background:rgba(0,0,0,.2);padding:1rem;border-radius:1rem">
             <div style="font-size:.75rem;color:#94a3b8">Ad ROAS</div>
             <div style="font-size:1.8rem;font-weight:800;color:var(--amber)">4.2x</div>
             <div style="font-size:.7rem;color:#94a3b8">Google Ads</div>
           </div>
        </div>
        <div style="margin-top:1rem;padding:1rem;background:rgba(14,165,233,.1);border-radius:1rem;border:1px solid rgba(14,165,233,.2);display:flex;align-items:center;gap:1rem">
           <span class="material-symbols-outlined" style="color:var(--teal)">smart_toy</span>
           <div>
             <div style="font-weight:700;font-size:.9rem;color:#fff">AI Receptionist Active</div>
             <div style="font-size:.75rem;color:var(--teal)">Handling calls 24/7</div>
           </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- SERVICES -->
<section id="services" class="rv" style="padding:6rem 0">
  <div class="wrap">
    <div style="text-align:center;margin-bottom:4rem">
      <h2 style="font-size:2.5rem;margin-bottom:1rem">Everything You Need</h2>
      <p style="color:var(--txt);max-width:50ch;margin:0 auto">We don't just "make websites". We build complete digital engines that generate leads, automate admin, and grow your revenue.</p>
    </div>
    <div class="card-grid stagger-load">
      <!-- Service 1 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">web</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">Website Design</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">High-performance websites designed to convert Hull locals into paying customers.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--amber);display:flex;align-items:center;gap:4px">Start Project <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
      <!-- Service 2 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">ads_click</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">Google Ads</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">Skip the queue. Appear at the top of Google when people search for your services.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--teal);display:flex;align-items:center;gap:4px">Get Visible <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
      <!-- Service 3 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">smart_toy</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">AI Automation</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">Missed calls cost money. Our AI answers phones, qualifies leads, and books jobs 24/7.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--amber);display:flex;align-items:center;gap:4px">Automate Now <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
      <!-- Service 4 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">campaign</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">Social Ads</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">Targeted Facebook & Instagram campaigns that put your brand in front of the right people.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--teal);display:flex;align-items:center;gap:4px">Launch Ads <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
      <!-- Service 5 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">storefront</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">Local SEO</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">Dominate the map pack. Ensure your business shows up first in local searches.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--amber);display:flex;align-items:center;gap:4px">Rank Higher <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
      <!-- Service 6 -->
      <div class="card-spot" style="padding:2rem">
        <div class="svc-icon"><span class="material-symbols-outlined">dataset</span></div>
        <h3 style="font-size:1.2rem;margin-bottom:.5rem;font-weight:700">CRM Systems</h3>
        <p style="font-size:.9rem;color:var(--txt);margin-bottom:1.5rem">Organise your leads, jobs, and invoices with a custom system built for your workflow.</p>
        <a href="#contact" style="font-size:.85rem;font-weight:700;color:var(--teal);display:flex;align-items:center;gap:4px">Get Organised <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>
      </div>
    </div>
  </div>
</section>

<!-- CONTACT -->
<section id="contact" class="rv" style="padding:6rem 0;background:var(--bg2)">
  <div class="wrap">
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:4rem;align-items:center">
      <div>
        <h2 style="font-size:2.5rem;font-weight:900;line-height:1.1;margin-bottom:1.5rem">Ready to Dominate<br><span style="color:var(--amber)">Your Market?</span></h2>
        <p style="margin-bottom:2rem;font-size:1.05rem;color:var(--txt)">Fill in the form, and we'll get back to you with a straightforward, no-obligation proposal.</p>
        <div style="background:var(--bg);padding:1.5rem;border-radius:1rem;border:1px solid var(--bdr)">
          <div style="font-weight:700;margin-bottom:1rem;color:#fff">Why Hull Web Fixers?</div>
          <ul style="list-style:none;display:flex;flex-direction:column;gap:.8rem;color:var(--txt2);font-size:.9rem">
            <li style="display:flex;gap:.6rem"><span class="material-symbols-outlined" style="color:var(--teal)">check_circle</span>Locally based in Hull (HU1)</li>
            <li style="display:flex;gap:.6rem"><span class="material-symbols-outlined" style="color:var(--teal)">check_circle</span>No long-term lock-in contracts</li>
            <li style="display:flex;gap:.6rem"><span class="material-symbols-outlined" style="color:var(--teal)">check_circle</span>We focus on ROI, not just "pretty pixels"</li>
          </ul>
        </div>
      </div>
      <form action="https://formspree.io/f/mlgwwjyn" method="POST" style="background:var(--bg);padding:2.5rem;border-radius:1.5rem;border:1px solid var(--bdr);box-shadow:0 20px 50px rgba(0,0,0,.3)">
        <h3 style="margin-bottom:1.5rem">Get Your Free Quote</h3>
        <input type="text" name="_gotcha" style="display:none">
        <input type="text" name="name" placeholder="Your Name" required autocomplete="name">
        <input type="email" name="email" placeholder="Email Address" required autocomplete="email">
        <select name="service" required>
          <option value="">I'm interested in...</option>
          <option>Website Design</option>
          <option>Google/Social Ads</option>
          <option>AI Automation</option>
          <option>Other</option>
        </select>
        <textarea name="message" rows="4" placeholder="Tell us about your project..."></textarea>
        <button class="btn-primary" style="width:100%;justify-content:center">Send Enquiry</button>
      </form>
    </div>
  </div>
</section>

<footer style="padding:4rem 0 2rem;border-top:1px solid var(--bdr);position:relative;overflow:hidden">
  <div class="wrap" style="position:relative;z-index:10">
    <div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:2rem">
       <div style="max-width:300px">
         <img src="logo.png" alt="Logo" style="height:32px;margin-bottom:1rem">
         <p style="font-size:.9rem;color:var(--txt)">Hull's dedicated digital growth agency. Building better businesses through design and automation.</p>
       </div>
       <div style="font-size:.9rem;color:var(--txt2)">
         <h4 style="margin-bottom:1rem">Contact</h4>
         <p>hello@hullwebfixers.co.uk</p>
         <p>Hull, East Yorkshire</p>
       </div>
    </div>
    <div style="margin-top:3rem;padding-top:1.5rem;border-top:1px solid var(--bdr);font-size:.8rem;color:var(--txt);text-align:center">
      &copy; 2025 Hull Web Fixers. All rights reserved. Built in Hull.
    </div>
  </div>
</footer>

<!-- GDPR Cookie with Animation -->
<div id="cookie-bar" style="position:fixed;bottom:-100px;left:50%;transform:translateX(-50%);background:var(--bg2);border:1px solid var(--amber);padding:1rem 2rem;border-radius:1rem;display:flex;align-items:center;gap:1.5rem;z-index:9999;transition:bottom .5s ease">
  <div style="color:#fff;font-size:.9rem">We use cookies to ensure you get the best experience.</div>
  <button onclick="accCookies()" style="background:var(--amber);border:none;padding:.5rem 1rem;border-radius:.5rem;font-weight:700;cursor:pointer">Accept</button>
</div>

<script>
// SCROLL EFFECTS & ANIMATION
const observer = new IntersectionObserver((entries)=>{
  entries.forEach(e=>{
    if(e.isIntersecting){
      e.target.classList.add('vis');
    }
  });
},{threshold:0.1});
document.querySelectorAll('.rv, .stagger-load').forEach(el=>observer.observe(el));

// SPOTLIGHT EFFECT
document.querySelectorAll('.card-spot').forEach(card=>{
  card.addEventListener('mousemove',e=>{
    const rect = card.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    card.style.setProperty('--x', x+'px');
    card.style.setProperty('--y', y+'px');
  });
});

// NAVBAR SCROLL
window.addEventListener('scroll',()=>{
  document.querySelector('.navbar').classList.toggle('scrolled', window.scrollY > 50);
});

// COOKIES
setTimeout(()=>{
  if(!localStorage.getItem('cookie_accepted')){
    document.getElementById('cookie-bar').style.bottom = '20px';
  }
}, 1000);
function accCookies(){
  localStorage.setItem('cookie_accepted','true');
  document.getElementById('cookie-bar').style.bottom = '-100px';
}
</script>
</body>
</html>
"""

# WRITE index.html
with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)
print(f"Index.html written ({len(html)} bytes).")

# COPY LOGO IF MISSING
logo_sum = "ChatGPT Image Feb 19, 2026, 11_43_56 PM.png"
if not os.path.exists("logo.png") and os.path.exists(logo_sum):
    shutil.copy(logo_sum, "logo.png")
    print("Logo copied.")

print("DONE.")
